### ISSUE TITLE
Installation fails due to tests

### ISSUE THREAD

**Issue by FelschR** [webpack-contrib/html-webpack-plugin#16]
## Description

Installation fails during test postbuild steps:
```
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! html-webpack-plugin@2.30.1 test: `jasmine`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the html-webpack-plugin@2.30.1 test script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\felix_schroeter\AppData\Roaming\npm-cache\_logs\2018-02-26T10_28_33_789Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! html-webpack-plugin@2.30.1 prepare: `npm run test`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the html-webpack-plugin@2.30.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\felix_schroeter\AppData\Roaming\npm-cache\_logs\2018-02-26T10_28_33_933Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: html-webpack-plugin@github:webpack-contrib/html-webpack-plugin.
npm ERR! package.json npm can't find a package.json file in your current directory.
```
full stacktrace:
[2018-02-26T10_28_38_931Z-debug.log](https://github.com/webpack-contrib/html-webpack-plugin/files/1758171/2018-02-26T10_28_38_931Z-debug.log)

## Environment

- Windows 10
- node 8.9.4
- npm 5.4.2.
- webpack 4.0.0

**Comment by afriedle** [comment]
Same here.

- Windows 10
- node 9.5
- npm 5.6.0
- webpack 4.0.0

**Comment by FelschR** [comment]
@phoggren Nice. The installation is working now.
The plugin itself doesn't seem to properly work for me though :/

**Comment by thescientist13** [comment]
@phoggren 
It seems there have been some changes since after the publicized release hash that have complicated the usage of this plugin a bit.  Here is the timeline as I understand it
1. webpack v4 release was announced a month or so ago to core teams / contributors / ecosystem to updater their projects
1. The [original owner](https://github.com/jantimon/html-webpack-plugin) of this plugin was unavailable for this period of time to make the needed upgrade changes, so the project was forked to **webpack-contrib** (this repo)
1.  A [PR was made](https://github.com/webpack-contrib/html-webpack-plugin/pull/3) which upgrade the repo to be webpack v4 compatible, the hash of that merge is [`a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e`](https://github.com/webpack-contrib/html-webpack-plugin/commit/a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e)
1.   Later that day some more changes were added, a couple of which may explain the issue being observed; [test script](https://github.com/webpack-contrib/html-webpack-plugin/commit/d66a1a9a0796945fc637d5ae5141f6267e6ecb58) and / or the [removal of bithound](https://github.com/webpack-contrib/html-webpack-plugin/commit/55aab64c518005835776bc1ba1353c731104e525) that triggered the tests to start running on install?
1.  webpack 4 was released and in the announcement with users directed to install from this repo with  the compat merge hash [`a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e`](https://github.com/webpack-contrib/html-webpack-plugin/commit/a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e)
1.  [Reports of [issues with tapable](https://github.com/webpack-contrib/html-webpack-plugin/pull/3#issuecomment-368288787) and [unit testing](https://github.com/webpack-contrib/html-webpack-plugin/pull/3#issuecomment-368325081) popped up that day
1. I opened an issue for tapable - https://github.com/webpack-contrib/html-webpack-plugin/issues/13
1. It was [resolved](https://github.com/webpack-contrib/html-webpack-plugin/pull/14) through a change and merged at [`6319451c00494ec32fea9176bfdcb7528185ab35`](https://github.com/webpack-contrib/html-webpack-plugin/commit/6319451c00494ec32fea9176bfdcb7528185ab35)

It seems that the reported issue (here) of the tests, is still in place though.

**Comment by thescientist13** [comment]
I also found with Yarn having to use the full GitHub URL worked best for me
```
$ yarn add https://github.com/webpack-contrib/html-webpack-plugin.git#6319451c00494ec32fea9176bfdcb7528185ab35 --dev
```

**Comment by thescientist13** [comment]
I forked this fork and got it working now.  Opened a PR to demonstrate - https://github.com/webpack-contrib/html-webpack-plugin/pull/17

**Comment by thescientist13** [comment]
Looks like this has been merged, so using this webpack-contrib repo, all issues should be resolved with hash [`1dee37e2696fd3990fe9be0a2945e465c0bb9a64`](https://github.com/webpack-contrib/html-webpack-plugin/commit/1dee37e2696fd3990fe9be0a2945e465c0bb9a64)
```shell
$ yarn add html-webpack-plugin@https://github.com/webpack-contrib/html-webpack-plugin.git#1dee37e2696fd3990fe9be0a2945e465c0bb9a64 --dev
```

[Passing on my CI server too](https://circleci.com/gh/ProvidenceGeeks/website-frontend/318)

thanks @michael-ciniawsky !! 🙏

**Comment by Lemaro86** [comment]
@thescientist13 i have such error:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/webpack-contrib/html-webpack-plugin.git /root/.npm/_git-remotes/git-https-github-com-webpack-contrib-html-webpack-plugin-git-1dee37e2696fd3990fe9be0a2945e465c0bb9a64-b699b9cb: undefined

**Comment by thescientist13** [comment]
@Lemaro86 
What version of npm?  This worked for me
```shell
$ npm -v
5.6.0
$ npm install html-webpack-plugin@https://github.com/webpack-contrib/html-webpack-plugin.git#1dee37e2696fd3990fe9be0a2945e465c0bb9a64 --save-dev
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN html-webpack-plugin@2.30.1 requires a peer of extract-text-webpack-plugin@^1.0.0 || ^2.0.0 || 3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@2.30.1 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN scratch@1.0.0 No description
npm WARN scratch@1.0.0 No repository field.
+ html-webpack-plugin@2.30.1
added 50 packages in 2.841s
```

Does it work on your local machine?  Maybe it has something to do with authorizing over HTTPS?  Maybe try with SSH?

**Comment by Lemaro86** [comment]
@thescientist13 It's working! Npm 5.6.0 too. 
I set "html-webpack-plugin": "^2.30.0", because its more newest than 2.30.1
Now my project haven't error with html-webpack-plugin
